### ISSUE TITLE
TOPページの改修

### ISSUE THREAD

**Issue by enkatsu** [tktomi/book-project#1]
# Indexの追加

- TOPページに各ページへのリンクを追加する
  - [ ] 書籍一覧(/books)
  - [ ] 著者一覧(/authors)
  - [ ] 出版社一覧(/companies)

**Comment by tktomi** [comment]
# 質問
- TOPページのcontrollerの開発の方法がわかりません 🤕

**Comment by enkatsu** [comment]
このコマンドでpageコントローラのindexアクションとかを作って、
config/route.rbに追加すればいいんじゃないの？ 🤔 

```bash
bundle exec rails g controller page index
```
